---
- name: Install basic packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - nss-mdns
    - net-tools
    - telnet
    - tcpdump
    - lsof
    - strace
    - wget
    - mlocate
    - setroubleshoot
    - setroubleshoot-server
