---
- name: Set SELinux to enforcing
  selinux:
    policy: targeted
    state: enforcing

- seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Enable tomcat access
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  when: ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and ansible_distribution_major_version == '7')

- name: Enable NGINX access
  firewalld:
    service: http
    permanent: true
    state: enabled
  when: ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and ansible_distribution_major_version == '7')
