---
- name: Restart and enable NGINX service
  service:
    state: restarted
    enabled: true
    name: nginx
  when: ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and ansible_distribution_major_version == '6')
